name: c_Test

on:
  workflow_dispatch:
  
  schedule:
    - cron: '55 2 * * *'

env:
  PASSWORD: ${{ secrets.PASSWORD }}
  TG_JSON: ${{ vars.TG_JSON }}

jobs:  
  login:  
    runs-on: ubuntu-22.04
  
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v3  
  
      - name: Set up Node.js  
        uses: actions/setup-node@v3  
       
  
      - name: Install dependencies  
        run: npm install puppeteer  
  
      - name: Create hostinfo 
        run: |
          curl -s https://sv.req.xx.kg/v > hostinfo.txt  
          echo "$PASSWORD" > password.txt  
          echo "$TG_JSON" > telegram.json  
          curl -s https://ident.me > ip.txt  
  
      - name: Login to website  
        run: |  
          set -e  
          xvfb-run --server-args="-screen 0 1280x1024x24" node serv00.js
