name: Web_Test

on:
  workflow_dispatch:
  
  schedule:
    - cron: '55 2 */2 * *'

env:
  HOSTINFO: ${{ vars.HOSTINFO }}
  PASSWORD: ${{ secrets.PASSWORD }}
  TG_JSON: ${{ vars.TG_JSON }}

jobs:  
  login:  
    runs-on: ubuntu-22.04
  
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v3  
  
      - name: Set up Node.js  
        uses: actions/setup-node@v3  
       
  
      - name: Install dependencies  
        run: npm install puppeteer  
  
      - name: Create hostinfo 
        run: |
          echo "$HOSTINFO" > hostinfo  
          echo "$PASSWORD" > password  
          echo "$TG_JSON" > telegram.json
          curl -s https://ident.me > ip
  
      - name: Login to website  
        run: |  
          set -e  
          xvfb-run --server-args="-screen 0 1280x1024x24" node serv00.js
